appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DJR7SZ0KxoDJQVOTsgIJ5gcHugRHyIVpVqwA3hEklq4PdKylxBT0DMFD59veufJQ9IqAptCgV0TVvJT8ELWHAou/iPFBpiO9qmjibjrXFcuaGI4ZdIMQNqn7fOw1lKogl9rFFIvJ6wnIV86IBW7baVERJuQLLVV3RoEOr+vSxcpQGOyybp+SeFfzgu8SFv3Bh3WGZJD4PI9F7i848lR1lBvX9j1S7vJ6JFdxQWJUljxdHegjxzqGT9aWAaT19T7wSFwm1EGHp+d1/cy+Rtsyq4Kg1ODef1WGWVVhOdfX8OWq22h3TSmdcXkLLUy9bwsj8PpERlgelNSk6pNgOJ++eadTajxwqYbRRm3aqmuKrG+m9wb6mp5Fq/8SaNkIJtpPfKp/rZ1xtX5wh4BEXZOtGGeKCIMtJN6eEGO0ZiSmCRVwvJiId/cEOflk7aLJbgqhTo3fBq5s+C0XlMM4001vKuxOGW+uxMhUgLD1aT+Xw4skyH+fU9+pwFTwEwUgdpT/a6sHSHC/HvJsYkJOJnxvaUWdfOQtaD71nC+xQsmfWxYNRZgiL2aBmjHGWtlW99fcX1heploHq2O2gWpD9Q8x+wJYm5K6xtVv55vzrYng7p3z5M2ihUg28u4NYcvUXNnKRvHejrYAC4GpKH7w2NSQmrtO4sQRiawoA5WBlJptPPo=}
bot:
  automerge: true
